server {
    listen 443 ssl;
    server_name _;

    # Coloque o nome EXATO dos arquivos gerados pelo mkcert
    ssl_certificate /etc/nginx/certs/192.168.1.4+2.pem;
    ssl_certificate_key /etc/nginx/certs/192.168.1.4+2-key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://laravel.test:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
    }
}